# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
$:.push File.expand_path("../lib", __FILE__)
require "capybara-page-object-patch"

Gem::Specification.new do |s|
  s.name = "capybara-page-object-patch"
  s.version = CapybaraPageObjectPatch::VERSION

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ari Russo"]
  s.description = "Patch for capybara-page-object"
  s.email = "ari@paperlesspost.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "Rakefile",
    "capybara-page-object-patch.gemspec",
    "spec/common_spec.rb",
    "spec/element/anchor_spec.rb",
    "spec/element/base_spec.rb",
    "spec/element/form_field_spec.rb",
    "spec/element/form_spec.rb",
    "spec/element/head_spec.rb",
    "spec/element/image_spec.rb",
    "spec/element/input_spec.rb",
    "spec/element/list_item_spec.rb",
    "spec/element/list_spec.rb",
    "spec/element/meta_spec.rb",
    "spec/element/select_spec.rb",
    "spec/element/table_row_spec.rb",
    "spec/element/table_spec.rb",
    "spec/element/textarea_spec.rb",
    "spec/fixtures/node.html",
    "spec/helper.rb",
    "spec/node_spec.rb",
    "spec/page_spec.rb"
  ]
  s.homepage = "http://github.com/paperlesspost/capybara-page-object"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Patch for capybara-page-object"

  s.add_development_dependency "bundler", "~> 1.5"
  s.add_development_dependency "jeweler", "~> 2.0", ">= 2.0.1"
  s.add_development_dependency "rspec", "~> 2.9", ">= 2.9.0"
  s.add_development_dependency "rake", "~> 10.4", ">= 10.4.2"

  s.add_runtime_dependency "capybara-page-object", "~> 0.6", ">= 0.6.1"

end
