# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
$:.push File.expand_path("../lib", __FILE__)
require "capybara-page-object-patch"

Gem::Specification.new do |s|
  s.name = "capybara-page-object-patch"
  s.version = CapybaraPageObjectPatch::VERSION

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ari Russo"]
  s.description = "Patch for capybara-page-object"
  s.email = "ari@paperlesspost.com"
  s.homepage    = "https://github.com/paperlesspost/capybara-page-object"
  s.files         = `git ls-files`.split("\n")
  s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.executables   = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }
  s.require_paths = ["lib"]
  s.summary = "Patch for capybara-page-object"

  s.add_development_dependency "bundler", "~> 1.5"
  s.add_development_dependency "jeweler", "~> 2.0", ">= 2.0.1"
  s.add_development_dependency "rspec", "~> 2.9", ">= 2.9.0"
  s.add_development_dependency "rake", "~> 10.4", ">= 10.4.2"

  s.add_runtime_dependency "capybara-page-object", "~> 0.6", ">= 0.6.1"

end
